GET http://localhost:4001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicm9iZXJ0byIsImlhdCI6MTYxNjE3MzI5NCwiZXhwIjoxNjE2MTc0MDAwfQ.Ii_vmptNPkWYvvt0SeAbXytEodtx4nTa5m5G2wTtDcU

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYmV0byIsImlhdCI6MTYxNjE3MzI3N30.SxLABefunjwcwM9feRQhWAirezlfjTDzGF6I2ppNRqg"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "beto"
}